default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: software_challenge_development
  username:

test:
  <<: *default
  database: software_challenge_test
  username:

production:
  <<: *default
  database: software_challenge_production
  username:
  password: <%= ENV['SOFTWARE-CHALLENGE_DATABASE_PASSWORD'] %>
